name: biocheck
description: We are a reintegration company that offers vitality and recovery programs. Our focus is on chronic fatigue, burnout and physical ailments. In this way we focus on 49% of the causes of long-term absenteeism due to illness.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  #  test:
  #    git:
  #      url:
  #        ssh:git@github.com:ZahidMahmood-Android/test.git

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: 0.16.1
  path_provider: ^1.6.24
  flutter_svg: ^0.18.1
  shared_preferences: ^0.5.12+4
  percent_indicator: ^2.1.7+4
  wave: ^0.1.0
  flutter_keyboard_visibility: ^4.0.0
  keyboard_visibility: ^0.5.6
  simple_gesture_detector: ^0.1.3
  get:
  retrofit: ^1.3.4
  dio: ^3.0.10
  json_annotation: ^3.0.1
  json_serializable: ^3.3.0
  rflutter_alert: ^1.1.0
  animations: ^1.1.2
  loading: ^1.0.2
  flutter_tts: ^2.0.0
  flutter_ibm_watson: ^0.0.1
  video_player: ^1.0.1
  connectivity: ^2.0.1
  webview_flutter: ^1.0.7
  tweenme: ^0.1.4
  adobe_xd: ^1.0.0+1
  google_speech: ^1.2.1
  audioplayer: 0.8.1
  audioplayer_web: 0.7.1
  floor: ^0.18.0

  flutter_blue: ^0.7.3
  countdown_flutter: ^0.1.2
  permission_handler: ^5.0.1+1
#  location_permissions: ^3.0.0+1
  location: ^3.2.4
  oscilloscope: ^0.0.3
#  charts_flutter: ^0.9.0
  fl_chart: ^0.10.1
  drawing_animation: ^0.1.3
#  connectivity_polar:
#    # When depending on this package from a real application you should use:
#    #   connectivity_polar: ^x.y.z
#    # See https://dart.dev/tools/pub/dependencies#version-constraints
#    # The example app is bundled with the plugin so we use a path dependency on
#    # the parent directory to use the current plugin's version.
#    path: connectivity_polar


dev_dependencies:
  flutter_test:
    sdk: flutter


  retrofit_generator: ^1.3.4+1
  floor_generator: ^0.18.0
  build_runner: ^1.10.3
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - videos/

  fonts:
    - family: RobotoLight
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  main_locale: en_US
  enabled: true
